name: build

on:
  push:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.xaml'
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.xaml'
    - '**.targets'
    - '**.props'

env:
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use

jobs:
  build:

    name: Build All Projects
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        project:
        - Part 1 - Displaying Data
        - Part 2 - MVVM
        - Part 3 - Navigation
        - Part 4 - Platform Features
        - Part 5 - CollectionView
        - Part 6 - AppThemes
        
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true
    
    - name: Install .NET workloads
      shell: pwsh
      run: |
        dotnet workload install android
        dotnet workload install ios
        dotnet workload install maccatalyst
        dotnet workload install maui
      
    - name: Build ${{ matrix.project }}
      run: dotnet build "${{ matrix.project }}/MonkeyFinder/MonkeyFinder.csproj"
